### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by maxih4** [tmb5cg/Fifa21-Autobidder#12]
Now the next problem. Sometimes the autobidder just stops and doesnt do anything anymore after opening the futbin Site.
Thats the log:

> [08:15:29] No more active bids

[08:15:29] Sending them to TL

[08:15:37] Players won: 0

[08:15:37] Players lost: 1

[08:15:37] Total investment:   0

[08:15:37] Total proj. return: 0

[08:15:37] Projected Profit:   0

[08:15:38] Cleared expired

[08:15:39] Now listing players

[08:15:51] Went to transfer list

[08:15:51] Gathering player prices...

Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\Max\AppData\Local\Programs\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Users\Max\Desktop\futbot\selFutBot\src\main.py", line 840, in run
    self.autobidder_reloaded.initializeBot()
  File "C:\Users\Max\Desktop\futbot\selFutBot\src\autobidder.py", line 31, in initializeBot
    self.start()
  File "C:\Users\Max\Desktop\futbot\selFutBot\src\autobidder.py", line 105, in start
    self.manageWatchlist()
  File "C:\Users\Max\Desktop\futbot\selFutBot\src\autobidder.py", line 176, in manageWatchlist
    self.finishWatchlist()
  File "C:\Users\Max\Desktop\futbot\selFutBot\src\autobidder.py", line 186, in finishWatchlist
    self.checkTransferlist()
  File "C:\Users\Max\Desktop\futbot\selFutBot\src\autobidder.py", line 195, in checkTransferlist
    transferlist_summary = self.helper.getTransferListSummary()
  File "C:\Users\Max\Desktop\futbot\selFutBot\src\helpers.py", line 1278, in getTransferListSummary
    p_sellprice = self.getFutbinPrice_opentab(p_id)
  File "C:\Users\Max\Desktop\futbot\selFutBot\src\helpers.py", line 2409, in getFutbinPrice_opentab
    price = int(price)
ValueError: invalid literal for int() with base 10: '-'
[4332:2652:0415/081611.510:ERROR:ssl_client_socket_impl.cc(924)] handshake failed; returned -1, SSL error code 1, net_error -113
[4332:2652:0415/081613.116:ERROR:ssl_client_socket_impl.cc(924)] handshake failed; returned -1, SSL error code 1, net_error -218

**Comment by maxih4** [comment]
DO you have a Discord or so? There are more mistakes and errors on windows that I would like to show you

**Comment by tmb5cg** [comment]
Yea for sure here's the discord: https://discord.gg/gd9UqAtr

Username is tmb5cg!

**Comment by maxih4** [comment]
Unfortunaterly is the invite link not available anymore

**Comment by tmb5cg** [comment]
I've remade the transfer list method so many times and I still don't love it, I'm not surprised it's causing issues...

It used to not require opening futbin tabs, instead it would pull prices from an open endpoint on Futbin, but I got IP blocked while debugging so I switched it to that. I'll brainstorm a better way of doing it

**Comment by tmb5cg** [comment]
Try this one https://discord.gg/dYFp6C34
