### ISSUE TITLE
I got this issue which is not in my chrome driver

### ISSUE THREAD

**Issue by crosstky** [tmb5cg/Fifa21-Autobidder#2]
this is the error i get in the cmd log :
"

Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "D:\apps\Fifa21-Autobidder-main\src\thread_runner.py", line 52, in run
    autobidder.manageWatchlist()
  File "D:\apps\Fifa21-Autobidder-main\src\autobidder.py", line 145, in manageWatchlist
    self.manageTransferlist()
  File "D:\apps\Fifa21-Autobidder-main\src\autobidder.py", line 155, in manageTransferlist
    self.helper.clearExpired()
  File "D:\apps\Fifa21-Autobidder-main\src\newhelpers.py", line 979, in clearExpired
    self.driver.find_element(By.XPATH, '/html/body/main/section/section/div[2]/div/div/div/section[4]/header/button').click()
  File "C:\Users\uosef\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\uosef\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\uosef\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/main/section/section/div[2]/div/div/div/section[4]/header/button"}
  (Session info: chrome=88.0.4324.190)

**Comment by tmb5cg** [comment]
Hi thanks I'll take a look in a little bit. Would love to have you get it running and give feedback

**Comment by tmb5cg** [comment]
Hi so it looks like you have the bot running? 

The issue is with the clearExpired button, it looks like there were no expired players. 

The bot was also calling the wrong method, instead of start() it was going straight to the watchlist. Thank you for pointing this out. 

Can you redownload the bot, and replace your src folder with the new one? and it should work.

**Comment by tmb5cg** [comment]
The GUI adding players is a bit broken at the moment... I'm updating it now hopefully by tonight it will work better, just realized this sorry!

**Comment by crosstky** [comment]
Well, 
I will give it a try now after the fix but I want to thanks you about your effort and appreciate that you shared such a wonderful project.
Thanks

**Comment by tmb5cg** [comment]
Thanks man that means more than you know. I updated the GUI and added some other things so let me know how it's working

**Comment by crosstky** [comment]
I gave a try again after you fix, It worked a good for like a couple of minutes until I got this error again . 
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "D:\apps\Fifa21-Autobidder-main\src\thread_runner.py", line 39, in run
    autobidder.start()
  File "D:\apps\Fifa21-Autobidder-main\src\autobidder.py", line 82, in start
    self.helper.bid_on_current_page(cardname, price_to_use, bidstomake_eachplayer, 0, "None")
  File "D:\apps\Fifa21-Autobidder-main\src\helpers.py", line 217, in bid_on_current_page
    players_on_page = self.getAllPlayerInfo()
  File "D:\apps\Fifa21-Autobidder-main\src\helpers.py", line 374, in getAllPlayerInfo
    time = cardinfo[22]
IndexError: list index out of range

aslo I have a couple of question :
1- the bot seams a little bit slow and i dont know if it is because safety settings or it something at my computer.
2- The bot seems to no rebid on lost player, I mean that as an example if a player has a value of 1000 and the bot bid on that player with 400 coin then someone else bid on me with 500 coins the bot doesn't over bid on the player and I lose the player even though there a still a big window to re bid on the player to get enough and good profit .


but overall the bot is very good except the problem I mentioned above.
Thanks for you support.

**Comment by tmb5cg** [comment]
Super helpful, someone reported the same error. Testing it now.

The slowness is on purpose, I'm going to add a speed button like 1.2x 1.3x 1.4x etc on the GUI soon! 

When the bot hits 'next page', there is a simple timer that waits 2 seconds before attempting to read all the players on the page. After 2 seconds, it reads everything in. It looks like if for whatever reason the page takes more than 2 seconds to load, the bot tries reading in data that doesn't exist. 

I also realized i broke the autobidder in the last update lol, I'm about to push an update and will let you know

**Comment by crosstky** [comment]
yeah I understand now.
Keep the good working up man , waiting to see this project in it's full potentials .

**Comment by tmb5cg** [comment]
Hey man, I made a bunch of updates. there should be little to no errors now!

**Comment by crosstky** [comment]
I gave it a try it is working very good now...
but I have a suggestion can you make the option to sell the won cards According to the futbin ...and also Add the option to sell this cards in price under the futbin price for quick...I don't know if this suggestions is possible...but trust this changes I'm telling you will make huge difference in your bit specially the feature of selling with futbin price and bid According to that price.
and again thanks for your huge effort in this flawless project.
