### ISSUE TITLE
Autobidder exception from thread 4 to 6

### ISSUE THREAD

**Issue by Tig0-0** [tmb5cg/Fifa21-Autobidder#20]
Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Users\Tig\AppData\Local\Programs\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\Tig\Desktop\Fifa21-Autobidder\src\main.py", line 840, in run
    self.autobidder_reloaded.initializeBot()
  File "C:\Users\Tig\Desktop\Fifa21-Autobidder\src\autobidder.py", line 31, in initializeBot
    self.start()
  File "C:\Users\Tig\Desktop\Fifa21-Autobidder\src\autobidder.py", line 105, in start
    self.manageWatchlist()
  File "C:\Users\Tig\Desktop\Fifa21-Autobidder\src\autobidder.py", line 176, in manageWatchlist
    self.finishWatchlist()
  File "C:\Users\Tig\Desktop\Fifa21-Autobidder\src\autobidder.py", line 186, in finishWatchlist
    self.checkTransferlist()
  File "C:\Users\Tig\Desktop\Fifa21-Autobidder\src\autobidder.py", line 195, in checkTransferlist
    transferlist_summary = self.helper.getTransferListSummary()
  File "C:\Users\Tig\Desktop\Fifa21-Autobidder\src\helpers.py", line 1278, in getTransferListSummary
    p_sellprice = self.getFutbinPrice_opentab(p_id)
  File "C:\Users\Tig\Desktop\Fifa21-Autobidder\src\helpers.py", line 2409, in getFutbinPrice_opentab
    price = int(price)
ValueError: invalid literal for int() with base 10: '-'
[17288:16536:0712/132602.797:ERROR:ssl_client_socket_impl.cc(980)] handshake failed; returned -1, SSL error code 1, net_error -200
[17288:16536:0712/132628.596:ERROR:ssl_client_socket_impl.cc(980)] handshake failed; returned -1, SSL error code 1, net_error -101
UMTITI
['Samuel Umtiti', 'UMTITI', '83', 'FC Barcelona', 'France', 'Rare', 'CB', '205600', '1065', '7800', '18', '7800', '0.85']
CAN
to remove: ['Emre Can', 'CAN', '82', 'Dortmund', 'Germany', 'Rare', 'CM', '208333', '768', '2900', '60', '0', '0.85']
VINÍCIUS
['Vinícius José de Oliveira Júnior', 'VINÍCIUS', '80', 'Real Madrid', 'Brazil', 'Rare', 'LW', '238794', '522', '3000', '28', '0', '0.85']
COMAN
['Kingsley Coman', 'COMAN', '84', 'FC Bayern', 'France', 'Rare', 'LM', '213345', '674', '7900', '26', '7900', '0.85']
[17288:16536:0712/132927.397:ERROR:ssl_client_socket_impl.cc(980)] handshake failed; returned -1, SSL error code 1, net_error -101
[13:29:34] Autobidder started

Exception in thread Thread-5:
Traceback (most recent call last):
  File "C:\Users\Tig\AppData\Local\Programs\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\Tig\Desktop\Fifa21-Autobidder\src\main.py", line 842, in run
    self.autobidder_reloaded.start()
  File "C:\Users\Tig\Desktop\Fifa21-Autobidder\src\autobidder.py", line 45, in start
    bidsallowed, bidstomake_eachplayer = self.helper.getWatchlistTransferlistSize()
  File "C:\Users\Tig\Desktop\Fifa21-Autobidder\src\helpers.py", line 727, in getWatchlistTransferlistSize
    self.driver.find_element(
  File "C:\Users\Tig\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\Tig\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Tig\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: window was already closed
  (Session info: chrome=91.0.4472.124)

[13:29:42] Autobidder started

Exception in thread Thread-6:
Traceback (most recent call last):
  File "C:\Users\Tig\AppData\Local\Programs\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\Tig\Desktop\Fifa21-Autobidder\src\main.py", line 842, in run
    self.autobidder_reloaded.start()
  File "C:\Users\Tig\Desktop\Fifa21-Autobidder\src\autobidder.py", line 45, in start
    bidsallowed, bidstomake_eachplayer = self.helper.getWatchlistTransferlistSize()
  File "C:\Users\Tig\Desktop\Fifa21-Autobidder\src\helpers.py", line 727, in getWatchlistTransferlistSize
    self.driver.find_element(
  File "C:\Users\Tig\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\Tig\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Tig\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: window was already closed
  (Session info: chrome=91.0.4472.124)

**Comment by Tig0-0** [comment]
File "C:\Users\Tig\AppData\Local\Programs\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\Tig\Desktop\Fifa21-Autobidder\src\main.py", line 826, in run
    self.autobidder_reloaded.manageWatchlist()
  File "C:\Users\Tig\Desktop\Fifa21-Autobidder\src\autobidder.py", line 116, in manageWatchlist
    page = self.driver.find_element_by_xpath("/html/body/main/section/section/div[1]/h1").text
  File "C:\Users\Tig\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\Tig\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\Tig\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Tig\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: window was already closed
  (Session info: chrome=91.0.4472.124)

[13:42:12] Bot broke - go_to_watchlist method

**Comment by Tig0-0** [comment]
Not sure if you could implement something to quickly restart the bot. The script seems to be having some problem with my transfer list and retrieving prices from futbin to list them. Bidding wise it work very well but whenever it breaks in TL part I need to restart everything and login.
