### ISSUE TITLE
Autobidder Exception in thread

### ISSUE THREAD

**Issue by antonioh501** [tmb5cg/Fifa21-Autobidder#25]
Hi, whenever I try to run the script (win10, python39) I get the errors below. Could you please help? Thank you

```
DevTools listening on ws://127.0.0.1:51774/devtools/browser/1fffb573-39c6-4df1-b301-d811c9331c2b
[16744:9860:1008/174323.266:ERROR:chrome_browser_main_extra_parts_metrics.cc(228)] crbug.com/1216328: Checking Bluetooth availability started. Please report if there is no report that this ends.
[16744:7852:1008/174323.266:ERROR:device_event_log_impl.cc(214)] [17:43:23.266] USB: usb_device_handle_win.cc:1048 Failed to read descriptor from node connection: Un dispositivo collegato al sistema non Þ in funzione. (0x1F)
[16744:9860:1008/174323.267:ERROR:chrome_browser_main_extra_parts_metrics.cc(231)] crbug.com/1216328: Checking Bluetooth availability ended.
[16744:7852:1008/174323.267:ERROR:device_event_log_impl.cc(214)] [17:43:23.267] USB: usb_device_handle_win.cc:1048 Failed to read descriptor from node connection: Un dispositivo collegato al sistema non Þ in funzione. (0x1F)
[16744:9860:1008/174323.268:ERROR:chrome_browser_main_extra_parts_metrics.cc(234)] crbug.com/1216328: Checking default browser status started. Please report if there is no report that this ends.
[16744:9860:1008/174323.282:ERROR:chrome_browser_main_extra_parts_metrics.cc(238)] crbug.com/1216328: Checking default browser status ended.
[16744:7852:1008/174327.706:ERROR:device_event_log_impl.cc(214)] [17:43:27.705] USB: usb_service_win.cc:258 Failed to get device driver name: Impossibile trovare elemento. (0x490)
[17:44:31]  - - - - Bot started - - - -

[17:44:31] Configuration saved

[17:44:31] Starting coins: 88922

[17:44:34] Autobidder started

Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\anton\AppData\Local\Programs\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Fifa21-Autobidder\src\main.py", line 840, in run
    self.autobidder_reloaded.initializeBot()
  File "C:\Fifa21-Autobidder\src\autobidder.py", line 31, in initializeBot
    self.start()
  File "C:\Fifa21-Autobidder\src\autobidder.py", line 45, in start
    bidsallowed, bidstomake_eachplayer = self.helper.getWatchlistTransferlistSize()
  File "C:\Fifa21-Autobidder\src\helpers.py", line 773, in getWatchlistTransferlistSize
    bidsallowed/num_players_to_bid_on) - 1
ZeroDivisionError: division by zero
```

**Comment by iancarv** [comment]
I would guess you didn't add any player to the player list
