### ISSUE TITLE
Exception in thread

### ISSUE THREAD

**Issue by Matgc04** [tmb5cg/Fifa21-Autobidder#27]
The program starts running fine and after 1 cycle of bidding and checking the watchlist I get this exception. To fix this I have to close the program and re-run it, but it'll eventually crash. 

[20:00:55] Autobidder started

Err update_autobidder_logs
[20:00:58] Bid to make on each player: 16

[20:01:05] LALA MARKET price: 750

[20:01:05] LALA stop price = buy ceiling (0.75) * (750) = 600

[20:01:05] BidRound 0 | MIN: 300 MAX: 400

Exception in thread Thread-5:
Traceback (most recent call last):
  File "C:\Users\gomez\Downloads\python\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "src\main.py", line 842, in run
    self.autobidder_reloaded.start()
  File "C:\Users\gomez\Desktop\Fifa21-Autobidder-main\src\autobidder.py", line 93, in start
    total_bids_made = self.helper.search_market_gather_players(cardname, max_price_to_pay, bidstomake_eachplayer, total_bids_made, "None", min_bid, max_bid)
  File "C:\Users\gomez\Desktop\Fifa21-Autobidder-main\src\helpers.py", line 242, in search_market_gather_players
    if ((curbid*2)<self.user_num_coins):
TypeError: '<' not supported between instances of 'int' and 'str'

**Comment by tmb5cg** [comment]
Closing bc old version of bot
