### ISSUE TITLE
is still working ?

### ISSUE THREAD

**Issue by GViatek** [tmb5cg/Fifa21-Autobidder#28]
Hi, i tried to run it, and run fine, open the chrome window and i login manualy,  

but i tried to add new player , put the url in the form and click button add, and got this error. 

find -name '*.pyc' -delete
#find -name __pycache__ -delete
python src/main.py
[01:11:39]  - - - - Bot started - - - - 

[01:11:39] Configuration saved

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/gonzalo/Escritorio/Fifa21-Autobidder-main/src/main.py", line 869, in run
    getFutbinDataAndPopulateTable(self.driver, self.queue, self.futbinurl)
  File "/home/gonzalo/Escritorio/Fifa21-Autobidder-main/src/helpers.py", line 2602, in getFutbinDataAndPopulateTable
    name = WebDriverWait(driver, 20).until(EC.visibility_of_element_located(
  File "/home/gonzalo/.local/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/home/gonzalo/Escritorio/Fifa21-Autobidder-main/src/main.py", line 233, in remove_player
    index = self.controller.table.router_tree_view.selection()[0]
IndexError: tuple index out of range
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/gonzalo/Escritorio/Fifa21-Autobidder-main/src/main.py", line 869, in run
    getFutbinDataAndPopulateTable(self.driver, self.queue, self.futbinurl)
  File "/home/gonzalo/Escritorio/Fifa21-Autobidder-main/src/helpers.py", line 2627, in getFutbinDataAndPopulateTable
    data = r.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/gonzalo/Escritorio/Fifa21-Autobidder-main/src/main.py", line 869, in run
    getFutbinDataAndPopulateTable(self.driver, self.queue, self.futbinurl)
  File "/home/gonzalo/Escritorio/Fifa21-Autobidder-main/src/helpers.py", line 2627, in getFutbinDataAndPopulateTable
    data = r.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

i use popOs (ubuntu based) and python3.

thanks

**Comment by Talaric0** [comment]
Yeah the bot seems to work alright on FUT webapp, but I'm also having trouble to add players using futbin's URL.

`Exception in thread Thread-21:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/Users/brunotalarico/code/Talaric0/projects/Fifa21-Autobidder/src/main.py", line 869, in run
    getFutbinDataAndPopulateTable(self.driver, self.queue, self.futbinurl)
  File "/Users/brunotalarico/code/Talaric0/projects/Fifa21-Autobidder/src/helpers.py", line 2627, in getFutbinDataAndPopulateTable
    data = r.json()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

maybe futbin changed something on their side

**Comment by GViatek** [comment]
I found a fix for this error en Json.

in helpers.py, found the function getFutbinDataAndPopulateTable

and found the line that make the requets to playerprices and add the var headers to make the request like a browers, if not u get a forbiden error. 

headers = {'User-Agent':"Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.17 (KHTML, like Gecko) Chrome/24.0.1312.27 Safari/537.17"}
    r = requests.get(
        'https://www.futbin.com/22/playerPrices?player={0}'.format(internal_id), headers=headers)

**Comment by lukecaccamo** [comment]
@GViatek this fix didn't work for me I still get a 403 with the added headers. I did notice a sessionId in the futbin cookie that might be necessary to avoid 403? As a workaround I made the request through the browser by opening the url through selenium, this request includes the browser cookie and returns success for me.

**Comment by GViatek** [comment]
@lukecaccamo make sure that u add the headers in the function request.get(url, headers=headers)

this works fine for me.

**Comment by lukecaccamo** [comment]
@GViatek yep I've done that, still 403 on my end

**Comment by tmb5cg** [comment]
Hi guys - cool to see some people using this, I actually have a different bot that I'm going to upload in a separate repo.

Full disclosure I got banned using it (on purpose, I was wasting too much time on this which I know sounds convenient) but I'm confident it's because I was doing 1200+ bids / 130k profit a day with an account that never played a game. Playing games is the key and max 1k bids a day

**Comment by tmb5cg** [comment]
Also the futbin url is from fifa 21 im pretty sure. You can always add players manually by using the txt file

**Comment by 0x2808** [comment]
Hey @tmb5cg, 
is there a new bot that works again ?

**Comment by tmb5cg** [comment]
hey I am uploading the new bot now!
