### ISSUE TITLE
error in clearGUIstats()

### ISSUE THREAD

**Issue by 90210moe** [tmb5cg/Fifa21-Autobidder#29]
Hello,

At the beginning, when running main.py, I directly receive this error message:

`Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\FUT_autobuyer_git\src\main.py", line 393, in <module>
    clearGUIstats()
  File "C:\Users\User\PycharmProjects\FUT_autobuyer_git\src\helpers.py", line 22, in clearGUIstats
    user_settings_current_date = str(config.get("Other", "todays_date"))
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\configparser.py", line 782, in get
    d = self._unify_values(section, vars)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\configparser.py", line 1153, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Other'`

I didnt change anything in the code.
Can you help me, fixing this error? Thank you

**Comment by tmb5cg** [comment]
Handled this error via Discord -- solution is redownload original config.ini and do not use auto-login, login manually
